import { TravelInfoDto } from 'src/travels/dto/travel-info.dto';

export const mockTravels: TravelInfoDto[] = [
  {
    id: 'wrdtr1',
    name: 'Tour in London',
    departureDate: '2024-02-01',
    returnDate: '2024-02-10',
    imageUrl: 'https://picsum.photos/id/230/450/200',
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
    price: 850,
    averageRating: 4.5,
  },
  {
    id: 'wrdtr2',
    name: 'Tour in Paris',
    departureDate: '2024-03-01',
    returnDate: '2024-03-10',
    imageUrl: 'https://picsum.photos/id/231/450/200',
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.`,
    price: 800,
    averageRating: 4.2,
  },
  {
    id: 'wrdtr3',
    name: 'Tour in Rome',
    departureDate: '2024-03-01',
    returnDate: '2024-03-04',
    imageUrl: 'https://picsum.photos/id/232/450/200',
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.`,
    price: 500,
    averageRating: 3.8,
  },
  {
    id: 'wrdtr4',
    name: 'Tour in Madrid',
    departureDate: '2024-03-11',
    returnDate: '2024-03-21',
    imageUrl: 'https://picsum.photos/id/233/450/200',
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting.`,
    price: 650,
    averageRating: 4.4,
  },
  {
    id: 'wrdtr5',
    name: 'Tour in Berlin',
    departureDate: '2024-03-01',
    returnDate: '2024-03-11',
    imageUrl: 'https://picsum.photos/id/234/450/200',
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.`,
    price: 550,
    averageRating: 4.5,
  },
  {
    id: 'wrdtr6',
    name: 'Tour in Amsterdam',
    departureDate: '2024-02-01',
    returnDate: '2024-02-07',
    imageUrl: 'https://picsum.photos/id/235/450/200',
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.`,
    price: 1200,
    averageRating: 4.9,
  },
  {
    id: 'wrdtr7',
    name: 'Tour in Barcelona',
    departureDate: '2024-03-01',
    returnDate: '2024-03-11',
    imageUrl: 'https://picsum.photos/id/236/450/200',
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.`,
    price: 620,
    averageRating: 4.1,
  },
  {
    id: 'wrdtr8',
    name: 'Tour in Vienna',
    departureDate: '2024-02-07',
    returnDate: '2024-02-14',
    imageUrl: 'https://picsum.photos/id/237/450/200',
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting.`,
    price: 750,
    averageRating: 4.3,
  },
  {
    id: 'wrdtr9',
    name: 'Tour in Prague',
    departureDate: '2024-03-22',
    returnDate: '2024-03-25',
    imageUrl: 'https://picsum.photos/id/238/450/200',
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.`,
    price: 690,
    averageRating: 4.4,
  },
  {
    id: 'wrdtr10',
    name: 'Tour in Lisbon',
    departureDate: '2024-03-01',
    returnDate: '2024-03-03',
    imageUrl: 'https://picsum.photos/id/239/450/200',
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.`,
    price: 250,
    averageRating: 3.1,
  },
  {
    id: 'wrdtr11',
    name: 'Tour in Athens',
    departureDate: '2024-03-04',
    returnDate: '2024-03-08',
    imageUrl: 'https://picsum.photos/id/240/450/200',
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.`,
    price: 320,
    averageRating: 2.5,
  },
  {
    id: 'wrdtr12',
    name: 'Tour in Istanbul',
    departureDate: '2024-03-09',
    returnDate: '2024-03-12',
    imageUrl: 'https://picsum.photos/id/241/450/200',
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting.`,
    price: 300,
    averageRating: 2.9,
  },
  {
    id: 'wrdtr13',
    name: 'Tour in Budapest',
    departureDate: '2024-02-21',
    returnDate: '2024-02-24',
    imageUrl: 'https://picsum.photos/id/242/450/200',
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.`,
    price: 430,
    averageRating: 3.8,
  },
  {
    id: 'wrdtr14',
    name: 'Tour in Moscow',
    departureDate: '2024-03-01',
    returnDate: '2024-03-05',
    imageUrl: 'https://picsum.photos/id/243/450/200',
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.`,
    price: 450,
    averageRating: 1.9,
  },
  {
    id: 'wrdtr15',
    name: 'Tour in Stockholm',
    departureDate: '2024-04-01',
    returnDate: '2024-04-05',
    imageUrl: 'https://picsum.photos/id/244/450/200',
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.`,
    price: 950,
    averageRating: 4.1,
  },
  {
    id: 'wrdtr16',
    name: 'Tour in Oslo',
    departureDate: '2024-03-08',
    returnDate: '2024-03-11',
    imageUrl: 'https://picsum.photos/id/245/450/200',
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.`,
    price: 1100,
    averageRating: 3.7,
  }
];