import { TravelInfoDto } from 'src/travels/dto/travel-info.dto';

export const mockTravels: TravelInfoDto[] = [
  {
    id: 'wrdtr1',
    name: 'Tour in London',
    departureDate: new Date('2024-02-01'),
    returnDate: new Date('2024-02-10'),
    imageUrl: 'https://picsum.photos/230/450/200',
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
    price: 850,
    averageRating: 4.5,
  },
  {
    id: 'wrdtr2',
    name: 'Tour in Paris',
    departureDate: new Date('2024-02-01'),
    returnDate: new Date('2024-02-10'),
    imageUrl: 'https://picsum.photos/231/450/200',
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.`,
    price: 800,
    averageRating: 4.2,
  },
  {
    id: 'wrdtr3',
    name: 'Tour in Rome',
    departureDate: new Date('2024-02-01'),
    returnDate: new Date('2024-02-10'),
    imageUrl: 'https://picsum.photos/232/450/200',
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.`,
    price: 500,
    averageRating: 3.8,
  },
  {
    id: 'wrdtr4',
    name: 'Tour in Madrid',
    departureDate: new Date('2024-02-01'),
    returnDate: new Date('2024-02-10'),
    imageUrl: 'https://picsum.photos/233/450/200',
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting.`,
    price: 650,
    averageRating: 4.4,
  },
  {
    id: 'wrdtr5',
    name: 'Tour in Berlin',
    departureDate: new Date('2024-02-01'),
    returnDate: new Date('2024-02-10'),
    imageUrl: 'https://picsum.photos/234/450/200',
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.`,
    price: 550,
    averageRating: 4.5,
  },
  {
    id: 'wrdtr6',
    name: 'Tour in Amsterdam',
    departureDate: new Date('2024-02-01'),
    returnDate: new Date('2024-02-10'),
    imageUrl: 'https://picsum.photos/235/450/200',
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.`,
    price: 1200,
    averageRating: 4.9,
  },
  {
    id: 'wrdtr7',
    name: 'Tour in Barcelona',
    departureDate: new Date('2024-02-01'),
    returnDate: new Date('2024-02-10'),
    imageUrl: 'https://picsum.photos/236/450/200',
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.`,
    price: 620,
    averageRating: 4.1,
  },
  {
    id: 'wrdtr8',
    name: 'Tour in Vienna',
    departureDate: new Date('2024-02-01'),
    returnDate: new Date('2024-02-10'),
    imageUrl: 'https://picsum.photos/237/450/200',
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting.`,
    price: 750,
    averageRating: 4.3,
  },
  {
    id: 'wrdtr9',
    name: 'Tour in Prague',
    departureDate: new Date('2024-02-01'),
    returnDate: new Date('2024-02-10'),
    imageUrl: 'https://picsum.photos/238/450/200',
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.`,
    price: 690,
    averageRating: 4.4,
  },
  {
    id: 'wrdtr10',
    name: 'Tour in Lisbon',
    departureDate: new Date('2024-02-01'),
    returnDate: new Date('2024-02-10'),
    imageUrl: 'https://picsum.photos/239/450/200',
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.`,
    price: 900,
    averageRating: 4.1,
  },
  {
    id: 'wrdtr11',
    name: 'Tour in Athens',
    departureDate: new Date('2024-02-01'),
    returnDate: new Date('2024-02-10'),
    imageUrl: 'https://picsum.photos/240/450/200',
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.`,
    price: 400,
    averageRating: 4.5,
  },
  {
    id: 'wrdtr12',
    name: 'Tour in Istanbul',
    departureDate: new Date('2024-02-01'),
    returnDate: new Date('2024-02-10'),
    imageUrl: 'https://picsum.photos/241/450/200',
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting.`,
    price: 550,
    averageRating: 4.2,
  },
  {
    id: 'wrdtr13',
    name: 'Tour in Budapest',
    departureDate: new Date('2024-02-01'),
    returnDate: new Date('2024-02-10'),
    imageUrl: 'https://picsum.photos/242/450/200',
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.`,
    price: 820,
    averageRating: 4.6,
  },
  {
    id: 'wrdtr14',
    name: 'Tour in Moscow',
    departureDate: new Date('2024-02-01'),
    returnDate: new Date('2024-02-10'),
    imageUrl: 'https://picsum.photos/243/450/200',
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.`,
    price: 650,
    averageRating: 4.3,
  },
  {
    id: 'wrdtr15',
    name: 'Tour in Stockholm',
    departureDate: new Date('2024-02-01'),
    returnDate: new Date('2024-02-10'),
    imageUrl: 'https://picsum.photos/244/450/200',
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.`,
    price: 850,
    averageRating: 4.1,
  },
  {
    id: 'wrdtr16',
    name: 'Tour in Oslo',
    departureDate: new Date('2024-02-01'),
    returnDate: new Date('2024-02-10'),
    imageUrl: 'https://picsum.photos/245/450/200',
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.`,
    price: 1100,
    averageRating: 4.7,
  }
];